[project]
name = "pyinstaller-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.8.0",
    "pyinstaller>=6.16.0",
    "playwright>=1.49.0",
]

[project.scripts]
pyinstaller-test = "pyinstaller_test.__main__:cli"
build = "pyinstaller_test.build:build"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "python-lsp-server>=1.13.1",
]
